version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Map port 8080 on localhost to port 8080 in the container
    volumes:
      - ./index.html:/app/index.html
      - ./styles.css:/app/styles.css
